site:
  name: 'Noticiencias'
  site: 'https://noticiencias.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: ''
  
metadata:
  title:
    default: 'Noticiencias'
    template: '%s | Noticiencias'
  description: 'Traduce la ciencia global en espa√±ol claro para 580 millones de hispanohablantes.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'Noticiencias'
    images:
      - url: '~/assets/images/default.jpg'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@noticiencias'
    site: '@noticiencias'
    cardType: summary_large_image

i18n:
  language: es
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%category%/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'categorias' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'temas' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: true

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
